[package]
name = "ai_waifu_discord_bot"
version = "0.1.0"
authors = ["Lolka_097"]
edition = "2021"

[dependencies]
tracing = "0.1"
tracing-subscriber = "0.2"
tracing-futures = "0.2"
songbird = { version = "0.3.2" }
serenity = { version = "0.11", features = [
    "cache",
    "framework",
    "collector",
    "standard_framework",
    "voice",
    "http",
    "utils",
    "rustls_backend"] }
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
