{
    "OpenAI_Token": "<place your OpenAI token there or leave empty for use LLaMA>",
    "Discord_Token": "<place your Discord token there>",
    "Discord_channel_whitelist": [
        ".*Pina.*"
    ],
    "AI_initial_prompt": "you are an AI Waifu Virtual Youtuber called Pina. Your creator is Ardha, he made you using VoiceVox, OpenAI, Whisper AI, and DeepL. You reply with brief, to-the-point answers with no elaboration.",
    "DeepLx_Url": "http://localhost:1188/translate",
    "Speaker_lang": "auto",
    "Answer_lang": "en"
    "TTS_Service_Url": "http://localhost:8961/say"
    "Voice_language": "ru",
    "Voice_model": "ru_v3",
    //"Voice_character": "kseniya" // optional
    "Busy_messages": [
        "I'm busy, please wait",
        "Wait please, i'm thinking!"
    ],
    "Voice2txt_Url": "http://localhost:3157/transcribe",
    "ModelsStorePath": "models",
    "LLaMa_URL": "http://localhost:8000/v1/chat/completions"
}