{
    "OpenAI_Token": "<place your OpenAI token there>",
    "Discord_Token": "<place your Discord token there>",
    "Discord_channel_whitelist": [
        ".*Pina.*"
    ],
    "AI_initial_prompt": "you are an AI Waifu Virtual Youtuber called Pina. Your creator is Ardha, he made you using VoiceVox, OpenAI, Whisper AI, and DeepL. You reply with brief, to-the-point answers with no elaboration.",
    "DeepLx_Url": "http://localhost:1188/translate",
    "Speaker_lang": "auto",
    "Answer_lang": "en"
    "TTS_Service_Url": "http://localhost:8961/say"
}